################################
#        Welcome to the        #
#       Barstool Newtech       #
#          Tweet Bot!          #
#    Created 01 / 16 / 2020    #
#       By Brad Campbell       #
################################

import tweepy;
import time;

# Authenticates to Twitter
auth = tweepy.OAuthHandler("KbhlyaJoDXqPPYEsKNf7zjmFa", "8W581WxA3KbD84FkvTSxmdMbyM82YNU2MNORR9yuJo5kmJgm1o");
auth.set_access_token("1170575028712288258-9yl1thmNtkLDWruztvVsHhpx7odJRL", "04KjUlh84UFVhOGtJZPHUeesDsot1EqspKQGu50Z32kOB");

# Creates API object
api = tweepy.API(
  auth, 
  wait_on_rate_limit=True, 
  wait_on_rate_limit_notify=True);
try:
  api.verify_credentials();
  print("************************");
  print("*    Welcome to the    *");
  print("*   Barstool Newtech   *");
  print("*      Tweet Bot!      *");
  print("************************");
  print("✓ Authentication Successful ✓\n\n");
except:
  print("An error occurred during authentication.\nVerify that Twitter API and Token Keys are correct.\n");


replyList = [];
def getRandomReply(replyCount):
  replyList.append("You are bad");
  replyList.append("You are awful");
  replyList.append("Your school isn't a real educational institute");
  replyList.append("Your degree isn't real");
  replyList.append("You aren't good at anything");
  replyList.append("When did we ask");
  replyList.append("Who? Cares.");
  replyList.append("You shouldn't be allowed on twitter");
  replyList.append("Why are you here?");
  replyList.append("Get off twitter. please.");
  replyList.append("You're trash at sports");
  replyList.append("No one is laughing");
  replyList.append("You're still the worst team in the 6A");
  replyList.append("Who actually enjoys you being on here?");
  replyList.append("Reported.");
  replyList.append("Who really actually asked?");
  replyList.append("In the course of human development, evolution has never failed like it has with you.");
  replyList.append("I know computers, and you know how to suck");
  replyList.append("This reply is generated by superior intellect");
  replyList.append("Congrats! No one likes you still");
  replyList.append("All your school has is crayons and cardboard");
  replyList.append("You're almost as bad as our robotics team");
  replyList.append("I could code faster than your pointguard runs");
  replyList.append("You should log off bro");
  replyList.append("Please just stop");
  replyList.append("This is worse than our bowling team");
  return replyList[replyCount];


def autoReply(statusID, replyCount):
  username = api.get_status(statusID).user.screen_name;
  api.update_status( 
    status = ('@'+ username + "  " + getRandomReply(replyCount)), 
    in_reply_to_status_id = statusID
  );


def main():
  #the fun part!!
  replyCount = 0;
  listID = 1217909351916167169; #ACTUAL
  #listID = 1218010243722043397; #FAKE WITH JUST DON-TYSON
  currentTweetID = (api.list_timeline(list_id = listID)[0].id) + 1;

  
  while (input("Type anything to terminate process:\n")):
    revTimeline = reversed(api.list_timeline(list_id = listID));
    for status in revTimeline:
      if (currentTweetID < status.id):
        currentTweetID = status.id;
        print("Status ID: " + str(status.id));
        if (replyCount <= len(replyList)):
          replyCount = (replyCount + 1);
        else:
          replyCount = 0;
        autoReply(status.id, replyCount);
      time.sleep(60); #1 minute loop


#final method call
main();
